version: '3.0'

services:
  api:
    container_name: test-billing_api
    build:
      context: api
      dockerfile: Dockerfile
    command: uvicorn --host=0.0.0.0 --port=8000 main:app
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./api/env/docker.env

  postgres:
    container_name: test-postgres
    image: library/postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d

  adminer:
    container_name: test-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
